usr/LICENSE.router usr/share/doc/mysql-router
usr/README.router usr/share/doc/mysql-router
usr/bin/mysqlrouter
usr/bin/mysqlrouter_keyring
usr/bin/mysqlrouter_passwd
usr/bin/mysqlrouter_plugin_info
usr/lib/mysql-router/libmysqlharness.so.1
usr/lib/mysql-router/libmysqlrouter.so.1
usr/lib/mysql-router/libmysqlrouter_http.so.1
usr/lib/mysql-router/libmysqlrouter_http_auth_backend.so.1
usr/lib/mysql-router/libmysqlrouter_http_auth_realm.so.1
usr/lib/mysql-router/libprotobuf-lite.so.3.11.4
usr/lib/mysqlrouter/plugin/http_auth_backend.so
usr/lib/mysqlrouter/plugin/http_auth_realm.so
usr/lib/mysqlrouter/plugin/http_server.so
usr/lib/mysqlrouter/plugin/keepalive.so
usr/lib/mysqlrouter/plugin/metadata_cache.so
usr/lib/mysqlrouter/plugin/mysql_protocol.so
usr/lib/mysqlrouter/plugin/rest_api.so
usr/lib/mysqlrouter/plugin/rest_metadata_cache.so
usr/lib/mysqlrouter/plugin/rest_router.so
usr/lib/mysqlrouter/plugin/rest_routing.so
usr/lib/mysqlrouter/plugin/router_protobuf.so
usr/lib/mysqlrouter/plugin/routing.so
usr/share/mysql/docs/sample_mysqlrouter.conf usr/share/doc/mysql-router
